# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66bc2b012a1dfbfe0583c96a29b508e39b997da67741ce4aa8d458bb7ea8743519167b7f09a57fd9d2e60a9ae0b12bc89c713bcbda493d7ac45fcac44a35825

test:
  secret_key_base: e14adee9ac3b284eca101cf39ac3770560b28093e1cf0d8bd5ad75d9ed093bd1b3d100160a12198f7fdb7ee942d328e0466b916aebedb6abae87d76d6e9f723b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
